-- MySQL Script generated by MySQL Workbench
-- Tue Jul  1 10:09:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema simpsons
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simpsons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simpsons` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `simpsons` ;

-- -----------------------------------------------------
-- Table `simpsons`.`capitulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpsons`.`capitulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(1000) NOT NULL,
  `numero_episodio` TINYINT NOT NULL,
  `temporada` TINYINT NOT NULL,
  `fecha_emision` DATE NULL DEFAULT NULL,
  `sinopsis` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `simpsons`.`personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpsons`.`personajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `ocupación` VARCHAR(50) NOT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `simpsons`.`frases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpsons`.`frases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(100) NOT NULL,
  `marca_tiempo` SMALLINT NULL DEFAULT NULL,
  `descripcion` LONGTEXT NULL DEFAULT NULL,
  `fk_personajes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frases_personajes_idx` (`fk_personajes` ASC) VISIBLE,
  CONSTRAINT `fk_frases_personajes`
    FOREIGN KEY (`fk_personajes`)
    REFERENCES `simpsons`.`personajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `simpsons`.`capitulos_has_personajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpsons`.`capitulos_has_personajes` (
  `fk_capitulos` INT NOT NULL,
  `fk_personajes` INT NOT NULL,
  PRIMARY KEY (`fk_capitulos`, `fk_personajes`),
  INDEX `fk_capitulos_has_personajes_personajes1_idx` (`fk_personajes` ASC) VISIBLE,
  INDEX `fk_capitulos_has_personajes_capitulos1_idx` (`fk_capitulos` ASC) VISIBLE,
  CONSTRAINT `fk_capitulos_has_personajes_capitulos1`
    FOREIGN KEY (`fk_capitulos`)
    REFERENCES `simpsons`.`capitulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_capitulos_has_personajes_personajes1`
    FOREIGN KEY (`fk_personajes`)
    REFERENCES `simpsons`.`personajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
